"""Immutable domain models for OpenEnterprise Twin."""

from openenterprise_twin.domain.company import (
    CompanyModel,
    CustomerSegment,
    DemandProfile,
    FinancialPolicy,
    MaterialPolicy,
    MaterialRequirement,
    Plant,
    Product,
    ResourceCapacity,
    ResourceRequirement,
)
from openenterprise_twin.domain.ledger import (
    ApprovalRecord,
    DecisionContent,
    DecisionEvidence,
    DecisionPacket,
    DecisionState,
    DecisionTransition,
    build_decision_packet,
    validate_transition,
)
from openenterprise_twin.domain.scenario import (
    MaterialPolicyChange,
    PolicyLevers,
    ResourcePolicyChange,
    Scenario,
    SegmentPaymentTermChange,
    SegmentProductPriceChange,
    validate_scenario_against_company,
)

__all__ = [
    "ApprovalRecord",
    "CompanyModel",
    "CustomerSegment",
    "DecisionContent",
    "DecisionEvidence",
    "DecisionPacket",
    "DecisionState",
    "DecisionTransition",
    "DemandProfile",
    "FinancialPolicy",
    "MaterialPolicy",
    "MaterialPolicyChange",
    "MaterialRequirement",
    "Plant",
    "PolicyLevers",
    "Product",
    "ResourceCapacity",
    "ResourcePolicyChange",
    "ResourceRequirement",
    "Scenario",
    "SegmentPaymentTermChange",
    "SegmentProductPriceChange",
    "build_decision_packet",
    "validate_scenario_against_company",
    "validate_transition",
]
